### PR TITLE
add Makie basic recipe

### LINKED ISSUE #463: Makie.jl plotting recipe missing

### PR DESCRIPTION
**Pull request by Moelf**
fix #463 

```julia
julia> p = Polynomial([1,0,3,4])
Polynomial(1 + 3*x^2 + 4*x^3)

julia> plot(p)
```
image

```julia
julia> scatter(p)
```
image

### CODE REVIEW

**Comment by Moelf** [comment]
one problem is that this doesn't work smartly:
```julia
julia> plot(p; axis=(; limits=(nothing, 3, nothing, nothing)))
```
image

**Comment by jverzani** [comment]
Awesome! 

I'm not sure what to expect in your example with `nothing` in the limits. Is there something on the `Polynomials` side we should be doing?

If not, let me know that this is good to merge and I'll merge it in.

**Comment by Moelf** [comment]
not much, per @asinghvi17 's comments on Slack, we can potentially make a new "full recipe" so that we can inspect the limits of the plot and produce `p.(xs)` accordingly.

But I think if user is superimposing a polynomial they probably need to manually make `xs` and `poly.(xs)` anyway.

I say we can merge.

**Comment by jverzani** [comment]
Great. Many thanks!

**Pull request merged**
