### PR TITLE
Add partial fraction decomposition (residue)

### PR DESCRIPTION
**Pull request by CrashBurnRepeat**
In working through some controls examples for a separate project, I came across the need for a function to do partial fraction decomposition (https://en.wikipedia.org/wiki/Partial_fraction_decomposition). This is a useful tool for solving Laplace Transforms and I could see it being useful to controls and DSP folks. 

I've also added tests and updates to README to go along with the residue function.

### CODE REVIEW

**Comment by jverzani** [comment]
Thanks. I haven't looked this over carefully yet, but at first glance it seems like it would fit quite naturally within @aytekinar 's [RationalFunctions](https://github.com/aytekinar/RationalFunctions.jl/) package. Any thoughts on this?

**Comment by aytekinar** [comment]
Thanks @jverzani --- indeed, [RationalFunctions](https://github.com/aytekinar/RationalFunctions.jl) could borrow from such `residue` functionality. Here, it depends on the point of view, I suppose. If you think [Polynomials](https://github.com/JuliaMath/Polynomials.jl) is a good fit, I can port it to RationalFunctions myself later on, when bumping up the version. Otherwise, a PR would be more than welcome to RationalFunctions.

**Comment by jverzani** [comment]
I'm glad you think it is a good fit. That seems best to me. Thanks as
always for the speedy response.

**Comment by CrashBurnRepeat** [comment]
Thanks everyone for the feedback. @aytekinar, since [RationalFunctions](https://github.com/aytekinar/RationalFunctions.jl) is a [Polynomials](https://github.com/JuliaMath/Polynomials.jl) extension, would it just be cutting and pasting code for the most part?

**Comment by aytekinar** [comment]
@CrashBurnRepeat, sorry, I couldn't understand your question exactly.

If you want to know if it would be hard for *you* to rewrite the code so that it would be part of `RationalFunctions` (only), but not `Polynomials`, of course, it won't be. I have done my best to reuse the existing code of `Polynomials`.

Otherwise, if you want to know if it would be hard for *anyone* to port the code to `RationalFunctions`, too, after it is accepted here, it won't be hard, either. I think we will just export the `residue` method from `RationalFunctions` and maybe write some wrapper function, if needed, to return the result in some other format.

**Comment by CrashBurnRepeat** [comment]
@aytekinar sorry for the ambiguity, I meant if I wanted to rewrite the code into a PR for `RationalFunctions`.  I can take a stab at that over the next few days if that works for you.

**Comment by aytekinar** [comment]
@jverzani and @CrashBurnRepeat, I have accepted the PR with two lines of change in aytekinar/RationalFunctions.jl#11. Unless you have similar plans for `Polynomials`, you can close the PR here.

Thank you, both of you, once more for the contribution.

**Comment by jverzani** [comment]
Great. Glad this all worked out!

**Pull request closed without merging**
