### PR TITLE
Update Pade type constructor for 0.6

### PR DESCRIPTION
**Pull request by ararslan**
Fixes the depwarn on 0.6

### CODE REVIEW

**Comment by jverzani** [comment]
Thanks, I was hoping someone would do this and keep v0.4 compatibility. I wasn't sure how.

**Comment by ararslan** [comment]
Hmm, looks like there's something I haven't done quite right here.

**Comment by ararslan** [comment]
Alright cool, _now_ it works.

**Comment by jverzani** [comment]
Great! Thanks.

**Pull request merged**
