### PR TITLE
Print imaginay unit as "i" with latex mimetype

### PR DESCRIPTION
**Pull request by gustaphe**
I refactored the `printcoefficient` function so that I could add a mimetype check, to make polynomials with complex coefficients print using `i` instead of `im`.

### CODE REVIEW

**Comment by jverzani** [comment]
Hey @gustaphe . Thanks! Sorry I haven't attended to this, but was working on a different PR. Now that that is done, I'd like to merge this one in. I noticed some testing issues. Could you look into these?

**Comment by gustaphe** [comment]
I think it's sorted now. I've since been looking into the printing ecosystem a bit more than I had when I first wrote this PR, and I'm not entirely sure I agree with handling it like this any more (especially since this PR bypasses operator precedence), but I still think this is an improvement. Do with it as you like :)

**Comment by jverzani** [comment]
How does this set of changes look to you?  It has a little extra to test for the leading one and, in theory, allows one to do something similar for different mimetypes.

```
imagsymbol(::Any) = "im"
imagsymbol(::MIME"text/latex") = "i"

# print complex numbers with parentheses as needed
function printcoefficient(io::IO, pj::S, j, mimetype) where {T, S <: Complex{T}}

    a = real(pj)
    b = imag(pj)
    
    hasreal = !iszero(a) || isnan(a) || isinf(a)
    hasimag = !iszero(b) || isnan(b) || isinf(b)

    if hasreal && hasimag
        print(io, "(")
        print(io, a)

        # print b
        if isone(b) || isone(-b)
            if hasneg(S) && b < 0
                print(io, showop(mimetype, "-"))
            else
                print(io, showop(mimetype, "+"))
            end
        else
            if hasneg(S) && b < 0 
                print(io, showop(mimetype, "-"))
                (showone(S) || !isone(-b)) && print(io, abs(b))
            else
                print(io, showop(mimetype, "+"))
                print(io, b)
            end
            print(io, showop(mimetype,"*"))
        end

        print(io, imagsymbol(mimetype)) 
        print(io, ")")

    elseif hasreal

        (j==0 || showone(S) || a != one(S)) && printcoefficient(io, a, j, mimetype)

    elseif hasimag

        b = imag(pj)
        (showone(S) || b != one(S)) && printcoefficient(io, b, j,  mimetype)
        (isnan(imag(pj)) || isinf(imag(pj))) && print(io, showop(mimetype, "*"))
        print(io, imagsymbol(mimetype))
        
    end        

    return nothing
end
```

**Comment by gustaphe** [comment]
Looks good! I'm apparently not thinking in Julia idioms yet :p

**Comment by jverzani** [comment]
It isn't very different from yours, save for the making the choice if `i` overrideable and the annoyance of printing 1 or not.. Do you want to modify your PR?

**Comment by gustaphe** [comment]
I'm sorry, I seem to have gone off on a bit of a tangent. And then I had a nightmerge. Anyway, how about this?

**Comment by jverzani** [comment]
This is great @gustaphe ! Thanks so much.

**Pull request merged**
