### PR TITLE
over_ring

### PR DESCRIPTION
**Pull request by jverzani**
Close issue #449 

A means of changing the element type (or symbol) for an abstract polynomial type.

### CODE REVIEW

**Comment by jverzani** [comment]
[This](https://docs.julialang.org/en/v1/manual/methods/#Building-a-similar-type-with-a-different-type-parameter) seems like the right place to find the generic name.

There the combination of the following would be suggested:

```{julia}
copyto!(similar(p, Eltype), p)
```

But you are right, our `similar` implementation is different (and maybe just wrong, as it treats a polynomial as an array and returns an array.)

Besides, the combination doesn't make sense with all the underlying types, like the tuple in `ImmutablePolynomial`, so this combined function should be exposed.

Just need to get the name correct. I think `over_ring` is a bit too mathematical,   `copy_with_eltype` too technical (but maybe the most expected?), and `reinterpret` not right either, as it doesn't really seem to match the generic usage.

**Comment by nsajko** [comment]
Regarding the name, I'd be fine with `copy_with_eltype` or maybe something like `copy_with_coeff_type`. `Base.reinterpret` is a wrong choice IMO, because it's for reinterpreting binary data, and here we're converting, not reinterpreting.

Regarding your implementation, I think it's possibly problematic, because it's lossy in the case of `FactoredPolynomial`, because the `coeffs` call converts the factored form to standard form, and then the `FactoredPolynomial` constructor has to search for the roots again.

**Comment by jverzani** [comment]
Thanks for the review. For now, it might be best to not export this in case a better name comes to mind. Let me know if you have any other thoughts here. If not, I'll merge and tag a new version.

**Comment by nsajko** [comment]
The implementation in the PR gives Julia trouble with type inference, causing run time dispatches and preventing type-inference of the final result. After `using Polynomials, JET, Test`:

```
julia> p = Polynomial((3, 2, 1))
Polynomial(3 + 2*x + x^2)

julia> Polynomials.copy_with_eltype(Float64, p)
Polynomial(3.0 + 2.0*x + 1.0*x^2)

julia> @report_opt Polynomials.copy_with_eltype(Float64, p)
═════ 1 possible error found ═════
┌ @ /tmp/Polynomials.jl/src/common.jl:477 Polynomials.copy_with_eltype(T, X, p)
│┌ @ /tmp/Polynomials.jl/src/common.jl:475 %2(%3)
││ runtime dispatch detected: %2::Type{Polynomial{Float64, _A}} where _A(%3::Vector{Int64})::Polynomial{Float64}
│└─────────────────────────────────────────


julia> @inferred Polynomials.copy_with_eltype(Float64, p)
ERROR: return type Polynomial{Float64, :x} does not match inferred return type Polynomial{Float64}
```

```
julia> ip = ImmutablePolynomial((3, 2, 1))
ImmutablePolynomial(3 + 2*x + x^2)

julia> Polynomials.copy_with_eltype(Float64, ip)
ImmutablePolynomial(3.0 + 2.0*x + 1.0*x^2)

julia> @inferred Polynomials.copy_with_eltype(Float64, ip)
ERROR: return type ImmutablePolynomial{Float64, :x, 3} does not match inferred return type ImmutablePolynomial{Float64}
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:35
 [2] top-level scope
   @ REPL[14]:1

julia> @report_opt Polynomials.copy_with_eltype(Float64, ip)
═════ 47 possible errors found ═════
```

I suspect the cleanest approach would be getting rid of the generic implementation, and having a separate implementation for each `AbstractPolynomial` subtype. This is what's suggested in the linked section of the Julia manual, anyway.

**Comment by jverzani** [comment]
Dang, just merged and tagged. Thanks, should have looked at emails first.

**Comment by jverzani** [comment]
It seems more cumbersome, but I can avoid this if I define it through:

```
copy_with_eltype(::Val{T}, ::Val{X}, p::P) where {T, X, S, Y, P <:AbstractPolynomial{S,Y}} = ⟒(P){T, X}(p.coeffs)
```

**Pull request merged**
