### PR TITLE
Superscript for HTML, combined `printexponent`

### PR DESCRIPTION
**Pull request by hamzaelsaawy**
A quick addition to show show HTML

### CODE REVIEW

**Comment by jverzani** [comment]
Thanks. Let me see if anyone weighs in on this, but it looks like a nice improvement.

**Comment by jverzani** [comment]
Care to have a go at this request while you are here? https://discourse.julialang.org/t/plaintext-output-in-ijulia-instead-of-html-display/20816

**Comment by hamzaelsaawy** [comment]
There are two parts to that discussion (of note, #167 has tests, which i forgot): the exponents are taken care of with `<sup>`, as this and #167 achieve, but the choice of html over LaTeX is inherent to [IJulia](https://github.com/JuliaLang/IJulia.jl/blob/2211a9c9b6821429254e88c60c6bb1d3c357e863/src/display.jl#L19).

**Comment by hardbyte** [comment]
Thanks! I can confirm that IJulia is rendering html over latex, and with this patch looks good:

screenshot from 2019-02-16 11-26-33

**Comment by jverzani** [comment]
Thanks again!

**Pull request merged**
