### PR TITLE
Fix Euclid's algorithm in `gcd`

### LINKED ISSUE #122: Avoid recursive function calls
### Description

We **should** avoid function recursion (as in `gcd`), and convert all recursive calls to `for` loops.

### Actual Behaviour

```julia
pnum = Poly([2.,5,1])
pden = Poly([1.,2,3])
magic_number = 170.10734737144486
magic_poly = pnum+pden*magic_number
gcd(magic_poly, pden) # <- StackOverflowError :(
```

### Desired Behaviour

```julia
gcd(magic_poly, pden) # simply returns after at most `degree(pden)` iterations.
# See the already cited Wikipedia page
```

### Fix Proposal

Will follow with a PR.

Credits to @neveritt for the example.

### PR DESCRIPTION
**Pull request by aytekinar**
Fixes #122.

### CODE REVIEW

**Comment by aytekinar** [comment]
Wait for a while... We have also some slight problem.

**Comment by aytekinar** [comment]
Seems to be correct, now.

**Comment by aytekinar** [comment]
ping @ararslan @jverzani ?

**Comment by jverzani** [comment]
Thanks. I'll merge. Limiting the number of iterations is definitely a good idea as that interesting example shows. I wonder if there will be any pushback on the calling of `truncate` here. If there is, we may need to revisit, but for now this seems like a good idea.

**Comment by aytekinar** [comment]
Thank you, @jverzani. I needed `truncate` there, as that specific example was resulting in `temp` being a `Poly` of degree 2 all the time. Then, the iterations (without the sentinel on `iter`) were looping indefinitely. Moreover, when you put the sentinel `iter` to finish in at most `degree(b)` iterations, the result popping out was wrong. But you are right, keeping this note on `truncate` would be helpful in the future, should one have problems...

**Pull request merged**
