### PR TITLE
fix some docstrings and docs issues

### PR DESCRIPTION
**Pull request by mileslucas**
Some small docs updates (outdated docstrings, etc.).

### CODE REVIEW

**Comment by mileslucas** [comment]
@jverzani I think the travis failures have to do with SSH keys. Are the `DOCUMENTER_KEY` (in travis) and the ssh key (in https://github.com/JuliaMath/Polynomials.jl/settings/keys) up to date, and does the github ssh key allow writing?

**Comment by jverzani** [comment]
Thanks.

Any thoughts why travis failed on the doc build? (https://travis-ci.org/github/JuliaMath/Polynomials.jl/jobs/677042941) I don't see any reason this would be different.

I also think you are right about the ssh keys needing to be correct. I'll have to track down who is the person who can do that.

**Comment by mileslucas** [comment]
looks like a random failure (url timeout retrieving an artifact). Restarting that job should fix it.

**Comment by jverzani** [comment]
Thanks!

**Pull request merged**
